"""fix relationships

Revision ID: 1e083121109a
Revises: 9996e6dbd14b
Create Date: 2026-07-31 11:55:21.886434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e083121109a'
down_revision: Union[str, None] = '9996e6dbd14b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_messages_convo_receiver_read', 'messages', ['convo_id', 'receiver_id', 'is_read'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_convo_receiver_read', table_name='messages')
    # ### end Alembic commands ###
