"""add user1_id and user2_id to conversations

Revision ID: 226dabc0f6e9
Revises: 3870c6a7865d
Create Date: 2026-07-28 16:48:27.568670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '226dabc0f6e9'
down_revision: Union[str, None] = '3870c6a7865d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tagged-friends')
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.drop_constraint(op.f('comments_user_id_fkey'), 'comments', type_='foreignkey')
    op.drop_constraint(op.f('comments_post_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.add_column('conversations', sa.Column('user1_id', sa.Integer(), nullable=True))
    op.add_column('conversations', sa.Column('user2_id', sa.Integer(), nullable=True))
    op.add_column('conversations', sa.Column('deleted_by_user1_at', sa.DateTime(), nullable=True))
    op.add_column('conversations', sa.Column('deleted_by_user2_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'users', ['user1_id'], ['id'])
    op.create_foreign_key(None, 'conversations', 'users', ['user2_id'], ['id'])
    op.add_column('messages', sa.Column('is_delivered', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('delivered_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'notifications', 'conversations', ['convo_id'], ['id'])
    op.drop_index(op.f('idx_tags_post_id'), table_name='tags')
    op.drop_index(op.f('idx_tags_user_id'), table_name='tags')
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('idx_tags_user_id'), 'tags', ['user_id'], unique=False)
    op.create_index(op.f('idx_tags_post_id'), 'tags', ['post_id'], unique=False)
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('messages', 'delivered_at')
    op.drop_column('messages', 'is_delivered')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'deleted_by_user2_at')
    op.drop_column('conversations', 'deleted_by_user1_at')
    op.drop_column('conversations', 'user2_id')
    op.drop_column('conversations', 'user1_id')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_post_id_fkey'), 'comments', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('comments_user_id_fkey'), 'comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.alter_column('comments', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('comments', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('tagged-friends',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('tagged-friends_post_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('tagged-friends_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tagged-friends_pkey'))
    )
    # ### end Alembic commands ###
