"""fixed

Revision ID: 352ccea69844
Revises: 8db3a7e81d79
Create Date: 2026-08-04 16:25:30.425896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '352ccea69844'
down_revision: Union[str, None] = '8db3a7e81d79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_post_like', 'likes', ['user_id', 'post_id'])
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('users_name_trigram', table_name='users', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('ix_users_active', 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_post_count'), 'users', ['post_count'], unique=False)
    op.create_index('ix_users_verified', 'users', ['is_verified'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_verified', table_name='users')
    op.drop_index(op.f('ix_users_post_count'), table_name='users')
    op.drop_index('ix_users_active', table_name='users')
    op.create_index('users_name_trigram', 'users', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_constraint('uq_user_post_like', 'likes', type_='unique')
    # ### end Alembic commands ###
