"""add message delivery fields

Revision ID: 3870c6a7865d
Revises: fbab6fef17a6
Create Date: 2026-07-23 13:05:27.403900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3870c6a7865d'
down_revision: Union[str, None] = 'fbab6fef17a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_delivered', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('delivered_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'delivered_at')
    op.drop_column('messages', 'is_delivered')
    # ### end Alembic commands ###
