"""fixed

Revision ID: 5d2181a1bd14
Revises: 352ccea69844
Create Date: 2026-08-07 12:24:39.007600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d2181a1bd14'
down_revision: Union[str, None] = '352ccea69844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_interest_interest', 'user_interests', ['interest'], unique=False)
    op.create_index('ix_user_interest_user', 'user_interests', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_interest', 'user_interests', ['user_id', 'interest'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_interest', 'user_interests', type_='unique')
    op.drop_index('ix_user_interest_user', table_name='user_interests')
    op.drop_index('ix_user_interest_interest', table_name='user_interests')
    # ### end Alembic commands ###
