"""add database indexes

Revision ID: 5ef87f82ccfc
Revises: 226dabc0f6e9
Create Date: 2026-07-30 16:52:50.926908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef87f82ccfc'
down_revision: Union[str, None] = '226dabc0f6e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_comments_post', 'comments', ['post_id'], unique=False)
    op.create_index('ix_comments_user', 'comments', ['user_id'], unique=False)
    op.create_index('ix_conversation_user1', 'conversations', ['user1_id'], unique=False)
    op.create_index('ix_conversation_user2', 'conversations', ['user2_id'], unique=False)
    op.create_index('ix_friend_requests_receiver', 'friend-requests', ['receiver_id'], unique=False)
    op.create_index('ix_friend_requests_sender', 'friend-requests', ['sender_id'], unique=False)
    op.create_index('ix_friend_requests_status', 'friend-requests', ['status'], unique=False)
    op.create_index('ix_friends_friend', 'friends', ['friend_id'], unique=False)
    op.create_index('ix_friends_user', 'friends', ['user_id'], unique=False)
    op.create_index('ix_likes_post', 'likes', ['post_id'], unique=False)
    op.create_index('ix_likes_user', 'likes', ['user_id'], unique=False)
    op.create_index('ix_messages_conversation', 'messages', ['convo_id'], unique=False)
    op.create_index('ix_messages_created', 'messages', ['created_at'], unique=False)
    op.create_index('ix_messages_receiver', 'messages', ['receiver_id'], unique=False)
    op.create_index('ix_messages_sender', 'messages', ['sender_id'], unique=False)
    op.create_index('ix_notifications_conversation', 'notifications', ['convo_id'], unique=False)
    op.create_index('ix_notifications_post', 'notifications', ['post_id'], unique=False)
    op.create_index('ix_notifications_user', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_posts_category', 'posts', ['category'], unique=False)
    op.create_index('ix_posts_created_at', 'posts', ['created_at'], unique=False)
    op.create_index('ix_posts_owner_id', 'posts', ['owner_id'], unique=False)
    op.create_index('ix_posts_published_at', 'posts', ['published_at'], unique=False)
    op.create_index('ix_posts_status', 'posts', ['status'], unique=False)
    op.create_index('ix_tags_post', 'tags', ['post_id'], unique=False)
    op.create_index('ix_tags_user', 'tags', ['user_id'], unique=False)
    op.create_index('ix_users_name', 'users', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_name', table_name='users')
    op.drop_index('ix_tags_user', table_name='tags')
    op.drop_index('ix_tags_post', table_name='tags')
    op.drop_index('ix_posts_status', table_name='posts')
    op.drop_index('ix_posts_published_at', table_name='posts')
    op.drop_index('ix_posts_owner_id', table_name='posts')
    op.drop_index('ix_posts_created_at', table_name='posts')
    op.drop_index('ix_posts_category', table_name='posts')
    op.drop_index('ix_notifications_user', table_name='notifications')
    op.drop_index('ix_notifications_post', table_name='notifications')
    op.drop_index('ix_notifications_conversation', table_name='notifications')
    op.drop_index('ix_messages_sender', table_name='messages')
    op.drop_index('ix_messages_receiver', table_name='messages')
    op.drop_index('ix_messages_created', table_name='messages')
    op.drop_index('ix_messages_conversation', table_name='messages')
    op.drop_index('ix_likes_user', table_name='likes')
    op.drop_index('ix_likes_post', table_name='likes')
    op.drop_index('ix_friends_user', table_name='friends')
    op.drop_index('ix_friends_friend', table_name='friends')
    op.drop_index('ix_friend_requests_status', table_name='friend-requests')
    op.drop_index('ix_friend_requests_sender', table_name='friend-requests')
    op.drop_index('ix_friend_requests_receiver', table_name='friend-requests')
    op.drop_index('ix_conversation_user2', table_name='conversations')
    op.drop_index('ix_conversation_user1', table_name='conversations')
    op.drop_index('ix_comments_user', table_name='comments')
    op.drop_index('ix_comments_post', table_name='comments')
    # ### end Alembic commands ###
