"""fixed

Revision ID: 8db3a7e81d79
Revises: 1e083121109a
Create Date: 2026-07-31 13:35:03.248026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8db3a7e81d79'
down_revision: Union[str, None] = '1e083121109a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.create_index(
            'ix_notifications_user_created',
            'notifications',
            ['user_id', 'created_at'],
            unique=False
        )

        op.add_column(
            'users',
            sa.Column(
                'post_count',
                sa.Integer(),
                nullable=False,
                server_default='0'
            )
        )

        op.add_column(
            'users',
            sa.Column(
                'comment_count',
                sa.Integer(),
                nullable=False,
                server_default='0'
            )
        )

        op.add_column(
            'users',
            sa.Column(
                'likes_given',
                sa.Integer(),
                nullable=False,
                server_default='0'
            )
        )

        op.add_column(
            'users',
            sa.Column(
                'likes_received',
                sa.Integer(),
                nullable=False,
                server_default='0'
            )
        )

        op.alter_column(
            'users',
            'email',
            existing_type=sa.VARCHAR(),
            nullable=False
        )

        op.alter_column(
            'users',
            'password',
            existing_type=sa.VARCHAR(),
            nullable=False
        )

        op.drop_index(
            'users_name_trigram',
            table_name='users',
            postgresql_ops={'name': 'gin_trgm_ops'},
            postgresql_using='gin'
        )

        op.create_index(
            'ix_users_active',
            'users',
            ['is_active'],
            unique=False
        )

        op.create_index(
            'ix_users_verified',
            'users',
            ['is_verified'],
            unique=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_verified', table_name='users')
    op.drop_index('ix_users_active', table_name='users')
    op.create_index('users_name_trigram', 'users', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'likes_received')
    op.drop_column('users', 'likes_given')
    op.drop_column('users', 'comment_count')
    op.drop_column('users', 'post_count')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    # ### end Alembic commands ###
